name: Deploy Cloud Run service

on:
  push:
    branches: [ main ]

jobs:
  deploy-cloud-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Set Google Cloud project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.GCP_REGISTRY_HOST }}/$GCP_PROJECT_ID/cloud-run-service:${{ github.sha }} .

      - name: Deploy Cloud Run service
        run: gcloud run deploy cloud-run-service --image ${{ secrets.GCP_REGISTRY_HOST }}/$GCP_PROJECT_ID/cloud-run-service:${{ github.sha }} --region us-central1
